# Only drop heads when killed directly by a player
player-kills-only: true

# Only drop player heads (you can also do this in "default chances" file
# by making all mobs except players have a 0% chance of dropping a head)
player-heads-only: false

# Whether to keep entity heads synced with the latest vanilla textures
refresh-textures: true

# When a player changes their skin, should old heads be updated to the
# new texture? Note: to refresh, heads must be mined or dropped
update-on-skin-change: false

# Enable the mechanic where any mob killed by a charged creeper explosion
# will drop its head with 100% probability * the spawn-cause modifier
# This setting will override "player-kills-only" (but not "player-heads-only")
charged-creeper-drops: true

# A Minecraft easter egg is that mobs named 'Dinnerbone' or 'Grumm' are
# upside down.. If you want their heads to share this trait, set to true
grumm-heads: true

# Percent increase in drop chance per looting level
looting-bonus: 0.4

# Uses non-linear (taylor series modifiers) when calculating drop chance
use-taylor-modifiers: true

# Only drop heads if the killer used an axe
must-use-axe: false

# Enable plugin Updater (checks for new versions with new head textures)
update-plugin: true

# (Optional) Whitelist of tools a player must be using for heads to drop
# If "must-use-axe" is enabled, this list will be ignored
# If empty, no special weapon/tool will be required to get heads
must-use:
#  - IRON_SWORD
#  - DIAMOND_AXE
#  - WOOD_HOE

# (Optional) Let certain tools have a higher chance of beheading
# The number is the percent increase in drop chance when using that tool
specific-tool-modifiers:
  GOLD_AXE: 3
  DIAMOND_AXE: 1
  IRON_AXE: 0.8
  STONE_AXE: 0.5
  DIAMOND_SWORD: 0.2
  IRON_SWORD: 0.1
  SHEARS: 0.05
